version: "3.7"
services:
  server:
    image: node:12-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      # used by postgres.js
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=test
      - PGPASSWORD=test
      - PGDATABASE=app
  db:
    image: postgres:13
    ports:
      - 4001:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=app
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    ports:
      - 4000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
      - PGADMIN_LISTEN_PORT=80
    volumes: #don't forget permissions to pgadmin4: $ sudo chown -R 5050:5050 volumes/pgadmin4
      - ./volumes/pgadmin4:/var/lib/pgadmin
      - ./volumes/pgadmin4:/pgadmin4/config_local.py
      - ./volumes/pgadmin4:/pgadmin4/servers.json

